import os
import re
from typing import Dict, Any, List

import docx
import pdfplumber

from src.ai.ai_jd_parser import parse_jd_ai


NOISE_LINES = [
    "generated by talentflow ai",
    "not added",
]


def clean_text(text: str) -> str:
    text = text or ""

    for noise in NOISE_LINES:
        text = re.sub(re.escape(noise), "", text, flags=re.I)

    return re.sub(r"\s+", " ", text).strip()


def clean_item(item: str) -> str:
    item = str(item or "").strip()
    item = item.lstrip("•-*0123456789. ").strip()

    if not item:
        return ""

    lower = item.lower()

    if "generated by talentflow ai" in lower:
        return ""

    if lower in ["not added", "na", "n/a", "none", "null"]:
        return ""

    return item


def unique_list(items: List[str]) -> List[str]:
    cleaned = []
    seen = set()

    for item in items:
        item = clean_item(item)

        if not item:
            continue

        key = item.lower()

        if key not in seen:
            cleaned.append(item)
            seen.add(key)

    return sorted(cleaned)


def extract_text(file_path: str) -> str:
    ext = os.path.splitext(file_path)[1].lower()

    if ext == ".pdf":
        parts = []

        with pdfplumber.open(file_path) as pdf:
            for page in pdf.pages:
                parts.append(page.extract_text() or "")

        return "\n".join(parts)

    if ext == ".docx":
        document = docx.Document(file_path)

        paragraphs = [p.text for p in document.paragraphs if p.text.strip()]
        table_text = []

        for table in document.tables:
            for row in table.rows:
                row_text = " ".join(
                    cell.text.strip()
                    for cell in row.cells
                    if cell.text.strip()
                )

                if row_text:
                    table_text.append(row_text)

        return "\n".join(paragraphs + table_text)

    if ext == ".txt":
        with open(file_path, "r", encoding="utf-8", errors="ignore") as file:
            return file.read()

    raise ValueError("Only PDF, DOCX, or TXT allowed")


def extract_email(text: str) -> str:
    match = re.search(
        r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+",
        text,
    )

    if not match:
        return ""

    email = match.group().strip()

    if email.lower() in ["not added", "na", "n/a"]:
        return ""

    return email


def extract_phone(text: str) -> str:
    match = re.search(r"(\+?\d{1,3}[\s-]?)?[6-9]\d{9}", text)

    if not match:
        return ""

    return match.group().strip()


def extract_apply_link(text: str) -> str:
    if "apply link: not added" in text.lower():
        return ""

    links = re.findall(r"https?://[^\s]+|www\.[^\s]+", text, re.I)

    for link in links:
        link = link.strip().rstrip(".,;)")

        if not link.startswith("http"):
            link = "https://" + link

        return link

    return ""


def extract_experience_years(text: str) -> float:
    patterns = [
        r"experience\s*[:\-]?\s*(\d+(?:\.\d+)?)",
        r"(\d+(?:\.\d+)?)\+?\s*(?:years|year|yrs|yr)",
        r"(\d+)\s*-\s*(\d+)\s*(?:years|year|yrs|yr)",
    ]

    for pattern in patterns:
        match = re.search(pattern, text, re.I)

        if match:
            try:
                return float(match.group(1))
            except Exception:
                return 0

    if any(word in text.lower() for word in ["fresher", "entry level", "internship"]):
        return 0

    return 0


def detect_job_type(text: str) -> str:
    lower = text.lower()

    mapping = {
        "Full-time": ["full time", "full-time", "fulltime"],
        "Part-time": ["part time", "part-time", "parttime"],
        "Internship": ["internship", "intern"],
        "Contract": ["contract", "contractual"],
        "Freelance": ["freelance"],
        "Temporary": ["temporary"],
        "Apprenticeship": ["apprenticeship", "apprentice"],
    }

    for label, patterns in mapping.items():
        if any(pattern in lower for pattern in patterns):
            return label

    return ""


def detect_work_mode(text: str) -> str:
    lower = text.lower()

    if any(x in lower for x in ["on-site", "onsite", "on site", "work from office"]):
        return "Onsite"

    if any(x in lower for x in ["remote", "work from home", "wfh"]):
        return "Remote"

    if "hybrid" in lower:
        return "Hybrid"

    if "field" in lower:
        return "Field Work"

    return ""


def detect_experience_level(text: str) -> str:
    lower = text.lower()

    if any(x in lower for x in ["fresher", "entry level", "entry-level", "intern"]):
        return "Entry Level"

    if any(x in lower for x in ["junior", "0-2", "1-2"]):
        return "Junior"

    if any(x in lower for x in ["mid level", "mid-level", "2-5", "3-5"]):
        return "Mid Level"

    if any(x in lower for x in ["senior", "5+", "lead"]):
        return "Senior"

    if "manager" in lower:
        return "Manager"

    if "director" in lower:
        return "Director"

    return ""


def extract_salary(text: str) -> Dict[str, str]:
    lower = text.lower()

    salary_line_match = re.search(
        r"salary\s*[:\-]?\s*([₹$€]?\s?[a-zA-Z]*\s?[0-9,.]+(?:\s?-\s?[0-9,.]+)?(?:\s?(?:lpa|per month|month|year|annum|pa))?)",
        text,
        re.I,
    )

    if salary_line_match:
        salary = salary_line_match.group(1).strip()
    else:
        patterns = [
            r"(₹|rs\.?|inr)\s?[0-9,.]+(?:\s?-\s?[0-9,.]+)?\s?(?:lpa|per month|month|year|annum|pa)?",
            r"(\$|usd)\s?[0-9,.]+(?:\s?-\s?[0-9,.]+)?\s?(?:per month|month|year|annum|pa)?",
            r"(€|eur)\s?[0-9,.]+(?:\s?-\s?[0-9,.]+)?",
        ]

        salary = ""

        for pattern in patterns:
            match = re.search(pattern, text, re.I)

            if match:
                salary = match.group().strip()
                break

    if not salary:
        return {
            "salary": "",
            "currency": "",
        }

    salary_lower = salary.lower()

    if "₹" in salary or "inr" in salary_lower or "rs" in salary_lower:
        currency = "INR"
    elif "$" in salary or "usd" in salary_lower:
        currency = "USD"
    elif "€" in salary or "eur" in salary_lower:
        currency = "EUR"
    elif salary.replace(",", "").replace(".", "").isdigit():
        currency = "INR"
    elif re.search(r"^\d", salary):
        currency = "INR"
    else:
        currency = ""

    return {
        "salary": salary,
        "currency": currency,
    }


def extract_title(raw_text: str) -> str:
    lines = [line.strip() for line in raw_text.splitlines() if line.strip()]

    bad_words = [
        "talentflow ai",
        "professional job description",
        "job description",
        "about us",
        "company",
        "location",
        "salary",
        "responsibilities",
        "requirements",
    ]

    for line in lines[:10]:
        lower = line.lower()

        if any(word in lower for word in bad_words):
            continue

        if len(line) <= 90 and len(line.split()) <= 10:
            return line

    return ""


def extract_simple_field(raw_text: str, label: str) -> str:
    pattern = rf"{label}\s*[:\-]\s*(.+)"
    match = re.search(pattern, raw_text, re.I)

    if not match:
        return ""

    value = match.group(1).strip()

    value = re.split(
        r"\s+(Salary|Experience|Job Type|Work Mode|Deadline|Status|Skills|HR Email|HR Phone|Apply Link)\s*:",
        value,
        flags=re.I,
    )[0].strip()

    if value.lower() in ["not added", "na", "n/a", "none", "null"]:
        return ""

    return value


def extract_skills_line(raw_text: str) -> List[str]:
    value = extract_simple_field(raw_text, "Skills")

    if not value:
        return []

    return unique_list([x.strip() for x in value.split(",")])


def split_section_items(text: str, headings: List[str]) -> List[str]:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    start = -1

    upper_headings = [heading.upper() for heading in headings]

    for i, line in enumerate(lines):
        normalized = line.strip().upper().replace(":", "")

        if normalized in upper_headings:
            start = i + 1
            break

    if start == -1:
        return []

    stop_words = [
        "REQUIREMENTS",
        "RESPONSIBILITIES",
        "RESPONSIBILITY",
        "DUTIES",
        "QUALIFICATIONS",
        "BENEFITS",
        "SKILLS",
        "ABOUT",
        "SALARY",
        "LOCATION",
        "APPLY",
        "JOB DESCRIPTION",
        "HR EMAIL",
        "HR PHONE",
        "APPLY LINK",
    ]

    collected = []

    for line in lines[start:]:
        normalized = line.upper().replace(":", "")

        if normalized in stop_words:
            break

        cleaned = clean_item(line)

        if cleaned:
            collected.append(cleaned)

    return unique_list(collected)


def fallback_parse(raw_text: str, clean: str) -> Dict[str, Any]:
    salary_data = extract_salary(raw_text)
    skills = extract_skills_line(raw_text)

    title = extract_title(raw_text)
    company = ""

    lines = [line.strip() for line in raw_text.splitlines() if line.strip()]

    if title:
        try:
            title_index = lines.index(title)
            if title_index + 1 < len(lines):
                possible_company = lines[title_index + 1].strip()
                if not any(x in possible_company.lower() for x in ["location", "salary", "experience"]):
                    company = possible_company
        except Exception:
            company = ""

    company = company or extract_simple_field(raw_text, "Company")
    location = extract_simple_field(raw_text, "Location")

    job_type = extract_simple_field(raw_text, "Job Type") or detect_job_type(clean)
    work_mode = extract_simple_field(raw_text, "Work Mode") or detect_work_mode(clean)

    if work_mode.lower() in ["on-site", "onsite", "on site"]:
        work_mode = "Onsite"

    responsibilities = split_section_items(
        raw_text,
        ["RESPONSIBILITIES", "RESPONSIBILITY", "DUTIES", "KEY RESPONSIBILITIES"],
    )

    requirements = split_section_items(
        raw_text,
        ["REQUIREMENTS", "REQUIRED SKILLS", "ELIGIBILITY"],
    )

    qualifications = split_section_items(
        raw_text,
        ["QUALIFICATIONS", "EDUCATION", "EDUCATIONAL QUALIFICATION"],
    )

    benefits = split_section_items(
        raw_text,
        ["BENEFITS", "PERKS", "WHAT WE OFFER"],
    )

    return {
        "title": title,
        "company": company,
        "location": location,
        "jobType": job_type,
        "workMode": work_mode,
        "experienceLevel": detect_experience_level(clean),
        "experienceYears": extract_experience_years(raw_text),
        "salary": salary_data["salary"],
        "currency": salary_data["currency"],
        "skills": skills,
        "technicalSkills": skills,
        "softSkills": [],
        "tools": [],
        "frameworks": [],
        "databases": [],
        "domains": [],
        "responsibilities": responsibilities,
        "requirements": requirements,
        "qualifications": qualifications,
        "benefits": benefits,
        "applyLink": extract_apply_link(raw_text),
        "contactEmail": extract_email(raw_text),
        "contactPhone": extract_phone(raw_text),
        "description": clean[:2000],
        "summary": "Job description extracted using fallback parser.",
        "jd_text": clean,
        "source": "fallback",
    }


def as_list(value: Any) -> List[str]:
    if value is None:
        return []

    if isinstance(value, list):
        raw = value
    elif isinstance(value, str):
        raw = [x.strip() for x in value.replace("|", ",").split(",")]
    else:
        raw = [str(value)]

    return unique_list(raw)


def merge_ai_with_fallback(
    ai_data: Dict[str, Any],
    fallback_data: Dict[str, Any],
) -> Dict[str, Any]:
    final_data = fallback_data.copy()

    for key, value in ai_data.items():
        if value not in ["", None, [], {}]:
            final_data[key] = value

    protected_keys = [
        "contactEmail",
        "contactPhone",
        "applyLink",
        "salary",
        "currency",
        "jobType",
        "workMode",
    ]

    for key in protected_keys:
        if fallback_data.get(key):
            final_data[key] = fallback_data[key]

    list_fields = [
        "skills",
        "technicalSkills",
        "softSkills",
        "tools",
        "frameworks",
        "databases",
        "domains",
        "responsibilities",
        "requirements",
        "qualifications",
        "benefits",
    ]

    for field in list_fields:
        final_data[field] = unique_list(
            as_list(fallback_data.get(field)) + as_list(ai_data.get(field))
        )

    all_skills = []

    for field in [
        "skills",
        "technicalSkills",
        "tools",
        "frameworks",
        "databases",
        "domains",
    ]:
        all_skills.extend(as_list(final_data.get(field)))

    final_data["skills"] = unique_list(all_skills)

    if str(final_data.get("workMode", "")).lower() in ["on-site", "onsite", "on site"]:
        final_data["workMode"] = "Onsite"

    if final_data.get("salary") and not final_data.get("currency"):
        salary = str(final_data.get("salary", ""))

        if salary.replace(",", "").replace(".", "").isdigit():
            final_data["currency"] = "INR"

    final_data["jd_text"] = fallback_data["jd_text"]
    final_data["source"] = f"{ai_data.get('source', 'AI')}+fallback"

    return final_data


def parse_jd(file_path: str) -> Dict[str, Any]:
    raw_text = extract_text(file_path)

    if not raw_text or not raw_text.strip():
        raise ValueError(
            "Empty JD or unsupported scanned file. Please upload a text-based PDF/DOCX/TXT."
        )

    clean = clean_text(raw_text)

    fallback_data = fallback_parse(raw_text, clean)
    ai_data = parse_jd_ai(clean)

    if ai_data:
        return merge_ai_with_fallback(ai_data, fallback_data)

    return fallback_data