import jsPDF from "jspdf";

const safe = (value, fallback = "Not added") => {
    if (Array.isArray(value)) return value.length ? value.join(", ") : fallback;
    return value ? String(value) : fallback;
};

export const downloadJobPdf = (job) => {
    const doc = new jsPDF("p", "mm", "a4");
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 18;

    const checkPage = () => {
        if (y > 265) {
            doc.addPage();
            y = 18;
        }
    };

    const addLine = (label, value) => {
        checkPage();

        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(30, 41, 59);
        doc.text(`${label}:`, 15, y);

        doc.setFont("helvetica", "normal");
        doc.setTextColor(71, 85, 105);

        const lines = doc.splitTextToSize(safe(value), pageWidth - 58);
        doc.text(lines, 48, y);

        y += Math.max(7, lines.length * 5);
    };

    const addSection = (title, value) => {
        checkPage();

        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(249, 115, 22);
        doc.text(title, 15, y);
        y += 7;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(51, 65, 85);

        const lines = doc.splitTextToSize(safe(value), pageWidth - 30);
        doc.text(lines, 15, y);

        y += lines.length * 5 + 7;
    };

    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, pageWidth, 34, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("TalentFlow AI", 15, 14);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text("Professional Job Description", 15, 23);

    y = 45;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(19);
    doc.setTextColor(15, 23, 42);
    doc.text(safe(job.title, "Job Description"), 15, y);
    y += 9;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(71, 85, 105);
    doc.text(safe(job.company, "Company not added"), 15, y);
    y += 10;

    addLine("Location", job.location);
    addLine("Salary", job.salary);
    addLine("Experience", job.experience);
    addLine("Job Type", job.jobType);
    addLine("Work Mode", job.workMode);
    addLine("Deadline", job.deadline);
    addLine("Status", job.status || "active");
    addLine("Skills", job.skills);
    addLine("HR Email", job.hrEmail);
    addLine("HR Phone", job.hrPhone);
    addLine("Apply Link", job.applyLink);

    y += 4;

    addSection("Job Description", job.description);
    addSection("Requirements", job.requirements);
    addSection("Responsibilities", job.responsibilities);

    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text("Generated by TalentFlow AI", 15, 287);

    const fileName = `${safe(job.title, "job-description")
        .replace(/[^a-z0-9]/gi, "_")
        .toLowerCase()}_jd.pdf`;

    doc.save(fileName);
};